// generated by build.rs -- don't edit directly

pub mod year2022 {
    pub mod day16;
}

use std::collections::BTreeMap;

pub struct Solution {
    pub part1: Option<fn(&str) -> String>,
    pub part2: Option<fn(&str) -> String>,
    pub tests: Option<fn() -> ()>,
}

// Clippy doesn't like the redundant to_string when the solution is
// already a String.
#[expect(clippy::redundant_clone, clippy::too_many_lines)]
pub fn build() -> BTreeMap<u16, BTreeMap<u8, Solution>> {
    let mut solutions: BTreeMap<u16, BTreeMap<u8, Solution>> = BTreeMap::new();

    solutions.entry(2022).or_default().insert(
        16,
        Solution {
            part1: Some(|input| year2022::day16::part1(input).to_string()),
            part2: None,
            tests: Some(year2022::day16::tests),
        },
    );

    solutions
}
